[project]
name = "ctf-cord"
version = ""
description = ""
authors = [
    {name = "samuzora", email = "lucastanyj@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}

[mypy]
files = [
    "src/**/*.py",
]
